# Generated by Django 2.2.6 on 2019-10-15 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('name_of_venue', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=25, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=30, null=True)),
                ('ticketless_event_name', models.CharField(blank=True, max_length=30, null=True)),
                ('assigend_seat_chart', models.ImageField(blank=True, upload_to='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_sale_end', models.DateTimeField()),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('open_door', models.TimeField(blank=True, null=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Posting', verbose_name='Posting')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(max_length=25)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('billing_address', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('Zip', models.CharField(blank=True, max_length=25, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=15, null=True)),
                ('cvv', models.CharField(blank=True, max_length=5, null=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='media')),
                ('business_license', models.FileField(blank=True, upload_to='media')),
                ('about_seller', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(max_length=25)),
                ('terms_condition', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralAdmissionSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_seat', models.CharField(blank=True, max_length=15, null=True)),
                ('gold_seat_availability', models.CharField(blank=True, max_length=5, null=True)),
                ('gold_seat_price', models.CharField(blank=True, max_length=5, null=True)),
                ('gold_is_enable', models.BooleanField(blank=True, default=False, null=True)),
                ('silver_seat', models.CharField(blank=True, max_length=15, null=True)),
                ('silver_seat_availability', models.CharField(blank=True, max_length=5, null=True)),
                ('silver_seat_price', models.CharField(blank=True, max_length=5, null=True)),
                ('silver_is_enable', models.BooleanField(blank=True, default=False, null=True)),
                ('bronze_seat', models.CharField(blank=True, max_length=15, null=True)),
                ('bronze_seat_availability', models.CharField(blank=True, max_length=5, null=True)),
                ('bronze_seat_price', models.CharField(blank=True, max_length=5, null=True)),
                ('bronze_is_enable', models.BooleanField(blank=True, default=False, null=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.Posting', verbose_name='Posting')),
            ],
        ),
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
